"""Added headers column

Revision ID: 38ce347f06b0
Revises: ceb3492c0510
Create Date: 2020-02-13 13:02:40.252741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38ce347f06b0'
down_revision = 'ceb3492c0510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('headers')
    # ### end Alembic commands ###
