"""Added is_deleted colum

Revision ID: 6b3737d63f88
Revises: 5ebf446e10e4
Create Date: 2020-04-09 16:23:59.882092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3737d63f88'
down_revision = '5ebf446e10e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('urls', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('urls', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('urls', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('urls', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_constraint('urls_user_id_fkey', 'urls', type_='foreignkey')
    op.create_foreign_key(None, 'urls', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'urls', 'users', ['created_by'], ['id'])
    op.drop_column('urls', 'user_id')
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_on')
    op.add_column('urls', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.create_foreign_key('urls_user_id_fkey', 'urls', 'users', ['user_id'], ['id'])
    op.drop_column('urls', 'updated_on')
    op.drop_column('urls', 'updated_by')
    op.drop_column('urls', 'is_deleted')
    op.drop_column('urls', 'created_on')
    op.drop_column('urls', 'created_by')
    # ### end Alembic commands ###
