"""Added inactive status and combined Index

Revision ID: 816bbbd74e1d
Revises: ce8f86f207f9
Create Date: 2020-05-01 00:04:31.370808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816bbbd74e1d'
down_revision = 'ce8f86f207f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('inactive_status_code', sa.Integer(), nullable=True))
    op.create_index('url_details_index', 'urls', ['url', 'payload', 'request_type', 'status_code', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url_details_index', table_name='urls')
    op.drop_column('urls', 'inactive_status_code')
    # ### end Alembic commands ###
