"""Added new table UrlCollection

Revision ID: 96a141cbe212
Revises: 816bbbd74e1d
Create Date: 2020-07-24 19:17:00.567359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96a141cbe212'
down_revision = '816bbbd74e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('request_body', sa.String(), nullable=True),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_key', sa.String(), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_collection_id'), 'url_collection', ['id'], unique=False)
    op.create_index(op.f('ix_url_collection_identifier'), 'url_collection', ['identifier'], unique=False)
    op.create_index('url_collection_index', 'url_collection', [sa.text('url DESC'), sa.text('request_url DESC'), sa.text('request_body DESC'), sa.text('request_type DESC'), sa.text('is_deleted DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url_collection_index', table_name='url_collection')
    op.drop_index(op.f('ix_url_collection_identifier'), table_name='url_collection')
    op.drop_index(op.f('ix_url_collection_id'), table_name='url_collection')
    op.drop_table('url_collection')
    # ### end Alembic commands ###
