"""Added request_type and payload

Revision ID: ceb3492c0510
Revises: 8c00d961a9f2
Create Date: 2020-02-11 15:58:45.197021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb3492c0510'
down_revision = '8c00d961a9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'uid', nullable=True, new_column_name = 'identifier')
    op.add_column('urls', sa.Column('payload', sa.String(), nullable=True))
    op.add_column('urls', sa.Column('request_type', sa.String(), nullable=False))
    op.create_index(op.f('ix_urls_identifier'), 'urls', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_urls_uid', 'urls', ['uid'], unique=False)
    op.drop_index(op.f('ix_urls_identifier'), table_name='urls')
    op.drop_column('urls', 'request_type')
    op.drop_column('urls', 'payload')
    op.drop_column('urls', 'identifier')
    # ### end Alembic commands ###
