version: '3.4'

services:
    postgresql:
        image: postgres:10.11
        container_name: postgresql
        hostname: postgresql
        environment:
            POSTGRES_DB: mockdb
            POSTGRES_USER: fyndlocal
            POSTGRES_PASSWORD: fynd@123
        ports:
            - "5432:5432"
        networks:
            - fyndnet
        volumes:
            - $fyndPostgresqlVolume:/var/lib/postgresql/data


networks:
    fyndnet:
        external:
            name: fyndnet
